# Generated by Django 4.2.16 on 2024-10-30 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('preparation_time', models.IntegerField(help_text='Tiempo en minutos')),
                ('cooking_time', models.IntegerField(help_text='Tiempo de coccion en minutos')),
                ('servings', models.IntegerField(help_text='Numero de porciones')),
                ('category', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Almuerzo'), ('dinner', 'Cena'), ('dessert', 'Postre')], max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='recipes/images/')),
                ('difficulty', models.CharField(choices=[('easy', 'Facil'), ('medium', 'Medio'), ('hard', 'Dificil')], max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
