# Generated by Django 4.2.16 on 2024-10-31 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodAppBlog', '0002_rename_recipe_recetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.CharField(help_text='Ej: 1 cucharada, 200ml', max_length=50)),
                ('descripcion_especial', models.TextField(blank=True, help_text='Ej: opcional, solo si es nescesario')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='foodAppBlog.recetas')),
            ],
        ),
    ]
